### ISSUE TITLE
Build error on vuepress-theme-cosmos 1.0.172

### ISSUE THREAD

**Issue by tansawit** [cosmos/vuepress-theme-cosmos#108]
I've been trying to migrate from the vanilla VuePress theme to using this theme. It seems to be working fine when running a local server `yarn start`. But when I try to build it gives the following error

```
wait Extracting site metadata...
tip Apply theme vuepress-theme-cosmos ...
warning [vuepress] Cannot resolve Layout.vue file in
 /Users/tansawit/bandprotocol/bandchain-docs/node_modules/vuepress-theme-cosmos
/Users/tansawit/bandprotocol/bandchain-docs/node_modules/vuepress-theme-cosmos/layouts,
 fallback to default layout: /Users/tansawit/bandprotocol/bandchain-docs/node_modules/@vuepress/core/lib/node/theme-api/Layout.fallback.vue
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin vuepress-plugin- ...
tip Apply plugin mathjax (i.e. "vuepress-plugin-mathjax") ...

✔ Client
  Compiled successfully in 38.02s

✔ Server
  Compiled successfully in 27.10s

Error in processing description: $page.content is undefined
Error in processing frontmatter: $page.content is undefined
Error in processing headings.
wait Rendering static HTML...
[Vue warn]: Error in render: "TypeError: Cannot read property 'banner' of undefined"

found in

---> <TmTopBanner>
       <Anonymous>
         <Root>
[Vue warn]: Error in render: "TypeError: Cannot read property 'banner' of undefined"

found in

---> <TmTopBanner>
       <Anonymous>
         <Root>
[Vue warn]: Error in render: "TypeError: Cannot read property 'banner' of undefined"

found in

---> <TmTopBanner>
       <Anonymous>
         <Root>
[Vue warn]: Error in render: "TypeError: Cannot read property 'banner' of undefined"

found in

---> <TmTopBanner>
       <Anonymous>
         <Root>
[Vue warn]: Error in render: "TypeError: Cannot read property 'banner' of undefined"

found in

---> <TmTopBanner>
       <Anonymous>
         <Root>
[Vue warn]: Error in render: "TypeError: Cannot read property 'banner' of undefined"

found in

---> <TmTopBanner>
       <Anonymous>
         <Root>
[Vue warn]: Error in render: "TypeError: Cannot read property 'banner' of undefined"

found in

---> <TmTopBanner>
       <Anonymous>
         <Root>
[Vue warn]: Error in render: "TypeError: Cannot read property 'banner' of undefined"

found in

---> <TmTopBanner>
       <Anonymous>
         <Root>
[Vue warn]: Error in render: "TypeError: Cannot read property 'banner' of undefined"

found in

---> <TmTopBanner>
       <Anonymous>
         <Root>
[Vue warn]: Error in render: "TypeError: Cannot read property 'banner' of undefined"

found in

---> <TmTopBanner>
       <Anonymous>
         <Root>
[Vue warn]: Error in render: "TypeError: Cannot read property 'banner' of undefined"

found in

---> <TmTopBanner>
       <Anonymous>
         <Root>
[Vue warn]: Error in render: "TypeError: Cannot read property 'banner' of undefined"

found in

---> <TmTopBanner>
       <Anonymous>
         <Root>
[Vue warn]: Error in render: "TypeError: Cannot read property 'banner' of undefined"

found in

---> <TmTopBanner>
       <Anonymous>
         <Root>
[Vue warn]: Error in render: "TypeError: Cannot read property 'banner' of undefined"

found in

---> <TmTopBanner>
       <Anonymous>
         <Root>
[Vue warn]: Error in render: "TypeError: Cannot read property 'banner' of undefined"

found in

---> <TmTopBanner>
       <Anonymous>
         <Root>
[Vue warn]: Error in render: "TypeError: Cannot read property 'banner' of undefined"

found in

---> <TmTopBanner>
       <Anonymous>
         <Root>
[Vue warn]: Error in render: "TypeError: Cannot read property 'banner' of undefined"

found in

---> <TmTopBanner>
       <Anonymous>
         <Root>
[Vue warn]: Error in render: "TypeError: Cannot read property 'banner' of undefined"

found in

---> <TmTopBanner>
       <Anonymous>
         <Root>
[Vue warn]: Error in render: "TypeError: Cannot read property 'banner' of undefined"

found in

---> <TmTopBanner>
       <Anonymous>
         <Root>
[Vue warn]: Error in render: "TypeError: Cannot read property 'banner' of undefined"

found in

---> <TmTopBanner>
       <Anonymous>
         <Root>
error Error rendering /404.html: false
undefined
error Error rendering /: false
undefined
error Error rendering /developer/: false
undefined
error Error rendering /developer/dapp-developers/: false
undefined
error Error rendering /developer/dapp-developers/supported-blockchains.html: false
undefined
error Error rendering /developer/technical-specifications/bandchain-cli-rest-endpoints.html: false
undefined
error Error rendering /developer/dapp-developers/requesting-data-from-bandchain.html: false
undefined
error Error rendering /developer/technical-specifications/obi.html: false
undefined
error Error rendering /developer/technical-specifications/owasm.html: false
undefined
error Error rendering /developer/dapp-developers/using-bandchain-data-evm.html: false
undefined
error Error rendering /developer/technical-specifications/remote-data-source-executor.html: false
undefined
error Error rendering /whitepaper/: false
undefined
error Error rendering /whitepaper/cosmos-ibc.html: false
undefined
error Error rendering /whitepaper/decentralized-validator-sampling.html: false
undefined
error Error rendering /whitepaper/introduction.html: false
undefined
error Error rendering /whitepaper/protocol-messages.html: false
undefined
error Error rendering /whitepaper/lite-client-protocol.html: false
undefined
error Error rendering /whitepaper/token-economics.html: false
undefined
error Error rendering /whitepaper/system-overview.html: false
undefined
error Error rendering /whitepaper/terminology.html: false
undefined
TypeError: Cannot read property 'banner' of undefined
    at Proxy.render (node_modules/vuepress-theme-cosmos/global-components/TmTopBanner.vue?c081:1:89)
    at VueComponent.Vue._render (/Users/tansawit/bandprotocol/bandchain-docs/node_modules/vue/dist/vue.runtime.common.dev.js:3538:22)
    at resolve (/Users/tansawit/bandprotocol/bandchain-docs/node_modules/vue-server-renderer/build.dev.js:8415:27)
    at waitForServerPrefetch (/Users/tansawit/bandprotocol/bandchain-docs/node_modules/vue-server-renderer/build.dev.js:8287:3)
    at renderComponentInner (/Users/tansawit/bandprotocol/bandchain-docs/node_modules/vue-server-renderer/build.dev.js:8426:3)
    at renderComponent (/Users/tansawit/bandprotocol/bandchain-docs/node_modules/vue-server-renderer/build.dev.js:8383:5)
    at resolve (/Users/tansawit/bandprotocol/bandchain-docs/node_modules/vue-server-renderer/build.dev.js:8451:9)
error Command failed with exit code 1.
```

Any advice on what might be causing this or what I should try to resolve it will be much appreciated.

**Comment by tansawit** [comment]
Nevermind. Found the solution in #86
